TrackiSwift/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TrackiSwift.Data;
using TrackiSwift.Models;
using TrackiSwift.Models.ViewModels;
using TrackiSwift.Utility;

namespace TrackiSwift.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class UserController : Controller
    {
        public ApplicationDbContext _db { get; set; }
        private RoleManager<IdentityRole> _roleManager;
        public UserController(ApplicationDbContext db, RoleManager<IdentityRole> roleManager)
        {
            _db = db;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Edit(string id)
        {
            var userFromDb = _db.Users.Find(id);

            if (userFromDb == null)
            {
                return NotFound();
            }
            var roles = _roleManager.Roles.Select(x => new SelectListItem
            {
                Value = x.Id,
                Text = x.Name
            }).ToList();
            ViewBag.Roles = roles;
            return View(userFromDb);
        }
        [HttpPost]
        public IActionResult Edit(UserVM user)
        {
            if (ModelState.IsValid)
            {

                ApplicationUser users = new ApplicationUser() 
                { 
                    Name=user.Name,
                    Email=user.Email,
                    Phone=user.Phone,
                    City=user.City,
                    StreetAddress=user.StreetAddress,
                    WardNo=user.WardNo,
                    Role=user.Role,
                };

                _db.Users.Update(users);
                _db.SaveChanges();
                TempData["success"] = "Edited Sucessfully";
                return RedirectToAction("Index");
            }
            return View(user);
        }


        #region API CALLS

        public IActionResult GetAll()
        {
            var userList = _db.ApplicationUsers.ToList();
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();

            foreach (var user in userList)
            {
                var roleId = userRole.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;


            }
            return Json(new { data = userList });
        }
        #endregion
    }
}

TrackiSwift/Controllers/OrderController.cs
using MeetingRoom.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using TrackiSwift.Models;

namespace TrackiSwift.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hostEnvironment;

        public OrderController(ApplicationDbContext db)
        {
            _db = db;
        }

        [AutoValidateAntiforgeryToken]
        //Action
        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<Order> objCoverTypeList = _db.Orders.ToList();
            return View(objCoverTypeList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Order obj)
        {
            if (ModelState.IsValid)
            {
                _db.Orders.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Created sucessfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var coverTypeFromDb = _db.Orders.FirstOrDefault(u => u.OrderId == Id);

            if (coverTypeFromDb == null)
            {
                return NotFound();
            }
            return View(coverTypeFromDb);
        }
        [HttpPost]
        public IActionResult Edit(Order obj)
        {
            _db.Orders.Update(obj);
            _db.SaveChanges();
            TempData["success"] = "Edited sucessfully";
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var coverTypeFromDb = _db.Orders.FirstOrDefault(u => u.OrderId == Id);

            if (coverTypeFromDb == null)
            {
                return NotFound();
            }
            return View(coverTypeFromDb);
        }
        [HttpPost]
        public IActionResult DeletePOST(int? Id)
        {
            var obj = _db.Orders.FirstOrDefault(u => u.OrderId == Id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Orders.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Deleted sucessfully";
            return RedirectToAction("Index");
        }

        public IActionResult Import(IFormFile file)
        {
            if (file == null)
            {
                TempData["error"] = "Please select a file.";
                return RedirectToAction("Index"); ;
            }
            try
            {
                using (var stream = new MemoryStream())
                {
                    file.CopyTo(stream);
                    using (var package = new ExcelPackage(stream))
                    {
                        var worksheet = package.Workbook.Worksheets[0]; // Assuming data is in the first worksheet

                        List<Order> orders = new List<Order>();

                        // Start from row 2 to skip headers
                        for (int row = 1; row <= worksheet.Dimension.Rows; row++)
                        {
                            Order order = new Order
                            {
                                ReceiverName = worksheet.Cells[row, 1].Value?.ToString(),
                                DeliveryAddress = worksheet.Cells[row, 2].Value?.ToString(),
                                Weight = Convert.ToDouble(worksheet.Cells[row, 3].Value),
                                Amount = Convert.ToDouble(worksheet.Cells[row, 4].Value),

                            };
                            orders.Add(order);
                        }
                        if (orders.Count > 0)
                        {
                            _db.Orders.AddRange(orders);
                            _db.SaveChanges();
                        }

                        TempData["success"] = "Imported successfully.";
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = $"Error during import: {ex.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

TrackiSwift/Views/Shared/_Layout.cshtml
@using TrackiSwift.Utility;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrackiSwift</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TrackiSwift.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TrackiSwift</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">User Management</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item " asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    <a class="dropdown-item " asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TrackiSwift - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>